version: 2.1

parameters:
  app2:
    type: boolean
    default: false

# See https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  job2:
    docker: # executor typeeeeeeee
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
    steps:
      - run:
          name: list files
          command: ls -l

workflows:
  app2:
    when: << pipeline.parameters.app2 >>
    jobs:
      - job2
