version: 2.1

parameters:
  app1:
    type: boolean
    default: false
  app2:
    type: boolean
    default: false

# See https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  job1:
    docker: # executor type
      - image: buildpack-deps:trusty # primary container will run Ubuntu Trusty
    steps:
      - run:
          name: list files
          command: ls -l
          
workflows:
  app1:
    when: << pipeline.parameters.app1 >>
    jobs:
      - job1
